#inputFilePath: McKesson-eCommerceFormularyWeekly/input.xlsx
inputFilePath: McKesson-eCommerceFormularyWeekly/McKesson eCommerce Formulary Weekly May 26, 2025.xlsx
outputFilePath: csv-McKessonMappingResults/output.csv
maxRowsPerFile: 0